### ISSUE TITLE
No divide function?

### ISSUE THREAD

**Issue by Ziao** [goessner/v2#1]
Hey,
Using the library and loving it so far!
I noticed that there is no divide function, or am I missing something? I could just do it manually but seeing how there's a scale function, it struck me as odd.

Thanks for making this,
Nick

**Comment by goessner** [comment]
Hi Nick,

this is in fact with intent. As you can simply use the scale function `v2.scl(u, 1/s)` it might be more advantageous to consider the special case when s becomes zero in the calling context as in a clueless divide function. Further you know, that dividing by a vector is not defined.

Thanks for using the library.
Stefan
